version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  storage-service:
    build: ./storage-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - auth-service
  collab-service:
    build: ./collab-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - auth-service
      - storage-service 