server:
  port: 8083

spring:
  application:
    name: collab-service
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    
  security:
    jwt:
      secret: your-secret-key-here-make-it-long-and-secure-in-production

# Collaboration service specific settings
collab:
  session:
    timeout: 3600 # 1 hour in seconds
    cleanup-interval: 300 # 5 minutes in seconds
  storage:
    service-url: http://localhost:8082 # storage service URL

# Logging
logging:
  level:
    com.drive.collab: DEBUG
    org.springframework.web.socket: DEBUG 